version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    ports:
      - "5678:5678"
    volumes:
      - ./n8n:/home/node/.n8n

  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
