services:
  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: default
      DOCKER_INFLUXDB_INIT_BUCKET: default
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admintoken
    volumes:
      - ./influxdb:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:10.4.0
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - influxdb

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      WEBHOOK_URL: http://localhost:5678/
      N8N_USER_FOLDER: /home/node/.n8n
      HOME: /home/node
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    user: "1000:1000"

volumes:
  n8n_data:
